[project]
name = "carbon-aware-compute"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "plotly>=6.0.1",
    "watttime>=1.3.2",
]
